# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sj2wbV9IWnsOe8fqyd0DsBeCb2d_59IL
"""

#calculator

x = float(input())
op = input()
y = float(input())
if op == "+":
  print(x + y)
elif op == "-":
  pirnt(x - y)
elif op == "*":
  print(x * y)
elif op == "/":
  print(x / y)